[package]
name        = "endringer-backend-git"
description = "gix-powered Git backend (endringer 0.19.2)"
version.workspace   = true
edition.workspace   = true
authors.workspace   = true
license.workspace   = true

[dependencies]
endringer-backend-core = { path = "../endringer-backend-core" }
anyhow = { workspace = true }
gix    = { workspace = true }
