[package]
name        = "knotra"
description = "knotra: multi-project VCS dashboard and bulk-operation tool."
readme      = "../../README.md"
version.workspace       = true
edition.workspace       = true
license.workspace       = true
authors.workspace       = true

[[bin]]
name    = "knotra"
path    = "src/main.rs"

[dependencies]
knotra-ui                   = { workspace = true }
knotra-vcs                  = { workspace = true }

iced                        = { workspace = true }
snora                       = { workspace = true }

chrono                      = { workspace = true }
dirs                        = { workspace = true }
rfd                         = { workspace = true }

anyhow                      = { workspace = true }
tokio                       = { workspace = true }
serde                       = { workspace = true }
serde_json                  = { workspace = true }
thiserror                   = { workspace = true }
toml                        = { workspace = true }
tracing                     = { workspace = true }
tracing-subscriber          = { workspace = true }
uuid                        = { workspace = true }

[dev-dependencies]
tempfile                    = { workspace = true }
